version: "3.7"
services:

  identidock:
    build: .
    expose:
      - "9090"
    environment:
      ENV: PROD
    links:
      - "dnmonster"
      - "redis"

  dnmonester:
    image: "amouat/dnmonester:1.0"

  redis:
    image: "redis:3.0"
