version: "3.7"
services:
  #test comment
  identidock:
    container_name: "identidock"
    build: .
    expose:
      - "9090"
    environment:
      ENV: PROD
    links:
      - "dnmonster"
      - "redis"

  dnmonster:
    container_name: "dnmonster"
    image: amouat/dnmonster:1.0

  redis:
    container_name: "redis"
    image: redis:3.0
